In [162]:
import numpy as np

In [168]:
class KMeans():
    def __init__(self, n_centroids,distance="eucledian",max_iter=1000):
        self.n_centriods = n_centroids
        self.iterations = max_iter
        self.centroids = 0

    def get_centroids(self):
        return self.centroids

        
    def compute_distances(self,X):
        samples = X.shape[0]
        features = X.shape[1]
        centroids = X[np.random.choice(samples, self.n_centriods, replace=False)]

        for it in range(self.iterations):

            lis = [[] for _ in range(self.n_centriods)]
            output = np.zeros((samples,self.n_centriods))
            for i in range(samples):
                for j in range(self.n_centriods):
                    output[i,j] = sum((X[i,:] - centroids[j,:])**2)

                lis[np.argmin(output[i,:])].append(X[i,:])

            for i in range(centroids.shape[0]):
                if lis[i]:
                    centroids[i,:] = np.mean(lis[i], axis=0)

        
        self.centroids = centroids

In [170]:
if __name__ == "__main__":
    X = np.random.rand(15,5)

    kmeans = KMeans(n_centroids=5)
    kmeans.compute_distances(X)
    print(kmeans.get_centroids())

[[0.78618042 0.67615685 0.16957055 0.14123229 0.49837941]
 [0.22859668 0.32964932 0.2391232  0.76447881 0.22193776]
 [0.17795146 0.51505165 0.82910281 0.49197479 0.21873212]
 [0.7896349  0.28922562 0.62681243 0.34597859 0.37391797]
 [0.6431351  0.25487006 0.58482922 0.72165537 0.91053399]]


# NOTE:
### It's wrong to initialie lis using [[]] * self.n_centriods. This creates a list with self.n_centriods references to the same empty list []. When you append data to lis[indexes[0]], you are actually appending to the same list referenced by all lis[i] elements. This results in incorrect clustering and centroid computation.

In [165]:
lis = [[] for _ in range(5)]
lis[0].append(9)
lis

[[9], [], [], [], []]

In [166]:
lis = [[]] * 5
lis[0].append(9)
lis

[[9], [9], [9], [9], [9]]