In [1]:
import numpy as np

In [103]:
class KMeans():
    def __init__(self, n_centroids,distance="eucledian",max_iter=1000):
        self.n_centriods = n_centroids
        self.iterations = max_iter
        self.centroids = 0

    def get_centroids(self):
        return self.centroids

        
    def compute_distances(self,X):
        samples = X.shape[0]
        features = X.shape[1]
        centroids = np.random.rand(self.n_centriods,features)
        print(centroids)
        for it in range(self.iterations):

            lis = [[] for _ in range(self.n_centriods)]
            output = np.zeros((samples,self.n_centriods))
            for i in range(samples):
                for j in range(self.n_centriods):
                    output[i,j] = sum((X[i,:] - centroids[j,:])**2)

                lis[np.argmin(output[i,:])].append(X[i,:])

            for i in range(centroids.shape[0]):
                centroids[i,:] = np.mean(lis[i], axis=0)

        
        self.centroids = centroids

In [104]:
if __name__ == "__main__":
    X = np.random.rand(10,5)

    kmeans = KMeans(n_centroids=3)
    kmeans.compute_distances(X)
    print(kmeans.get_centroids())

[[0.33515363 0.10153459 0.27056983 0.67718923 0.51012562]
 [0.51003317 0.37717044 0.95934713 0.20234759 0.42550482]
 [0.01824159 0.52181334 0.67744702 0.65889168 0.47534307]]
[[0.58441862 0.39394329 0.14359367 0.70459217 0.22477647]
 [0.55679626 0.42751225 0.85238337 0.24199053 0.63585805]
 [0.23887297 0.68871644 0.36096531 0.27209281 0.72624301]]


# NOTE:
### It's wrong to initialie lis using [[]] * self.n_centriods. This creates a list with self.n_centriods references to the same empty list []. When you append data to lis[indexes[0]], you are actually appending to the same list referenced by all lis[i] elements. This results in incorrect clustering and centroid computation.

In [108]:
lis = [[] for _ in range(5)]
lis[0].append(9)
lis

[[9], [], [], [], []]

In [109]:
lis = [[]] * 5
lis[0].append(9)
lis

[[9], [9], [9], [9], [9]]