In [4]:
import torch
import numpy as np

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"  # Cuda to run on GPU!

### Initializing Tensors

In [6]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [7]:
torch.empty(size=(3, 3)) # data of memory unchanged

tensor([[1.3020e+10, 1.2766e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
torch.zeros((3, 3)) # tensor of zeros initialized

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.rand((3, 3)) # matrix with random values initialized

tensor([[0.5302, 0.2642, 0.5809],
        [0.6712, 0.7531, 0.9528],
        [0.4710, 0.4737, 0.6639]])

In [10]:
torch.ones((3, 3)) # matrix with ones initialized

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.eye(5, 5) # Identity matrix initialized

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
torch.arange(start=0, end=5, step=2)  # vector with start,end and step size initialized

tensor([0, 2, 4])

In [13]:
torch.linspace(start=0.1, end=1, steps=10) # 10 values between 0.1 and 1 equally divided

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [14]:
torch.empty(size=(1, 5)).normal_(mean=0, std=1)

tensor([[ 0.5316,  0.2451, -1.3502,  1.4384, -0.2892]])

In [15]:
torch.empty(size=(1, 5)).uniform_(0, 1) 

tensor([[0.3447, 0.5230, 0.4673, 0.4543, 0.4521]])

In [22]:
torch.diag(torch.rand(3)) # puts values of diagonal 

tensor([[0.5407, 0.0000, 0.0000],
        [0.0000, 0.5317, 0.0000],
        [0.0000, 0.0000, 0.1719]])

In [23]:
torch.arange(4)

tensor([0, 1, 2, 3])

### Convert numpy array to tensor and vice-versa

In [ ]:
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_array_again = tensor.numpy()

### Tensor Math & Comparison Operations

In [24]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])
print(x,y)

tensor([1, 2, 3]) tensor([9, 8, 7])


### Addition

In [28]:
z1 = torch.empty(3)
torch.add(x, y, out=z1)
z1

tensor([10., 10., 10.])

In [27]:
z2 = torch.add(x, y)
z2

tensor([10, 10, 10])

In [26]:
z = x + y
z

tensor([10, 10, 10])

### Subtraction

In [29]:
z = x - y 
z

tensor([-8, -6, -4])

### Division

In [30]:
z = torch.true_divide(x, y) 
z

tensor([0.1111, 0.2500, 0.4286])

In [31]:
x/y

tensor([0.1111, 0.2500, 0.4286])

### Inplace Operations

In [32]:
# -- Inplace Operations --
t = torch.zeros(3)

t.add_(x)  # Whenever we have operation followed by _ it will mutate the tensor in place
t
# NOTE: t = t + x is not inplace, bit confusing.

tensor([1., 2., 3.])

### Exponentiation

In [33]:
z = x.pow(2)  # z = [1, 4, 9]
z = x**2  # z = [1, 4, 9]
z

tensor([1, 4, 9])

### Comaparsion

In [34]:
z = x > 0  # Returns [True, True, True]
print(z)
z = x < 0  # Returns [False, False, False]
print(z)

tensor([True, True, True])
tensor([False, False, False])


### Matrix Multiplication

In [35]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)  # Matrix multiplication of x1 and x2, out shape: 2x3
x3 = x1.mm(x2)  # Similar as line above
x3

tensor([[1.6036, 0.8322, 1.4877],
        [1.8939, 1.0413, 1.5948]])

### Matrix Exponentiation

In [36]:
matrix_exp = torch.rand(5, 5)
print(matrix_exp.matrix_power(3))  

tensor([[1.9845, 2.2630, 1.5041, 2.5477, 2.5372],
        [1.7166, 1.8140, 1.2379, 2.1772, 2.2259],
        [3.1912, 3.4204, 2.4400, 4.3027, 4.3494],
        [2.8229, 3.2086, 2.4919, 4.2319, 4.1824],
        [1.4388, 1.5726, 1.0855, 1.8740, 1.8938]])


### Element wise Multiplication

In [37]:
z = x * y
z

tensor([ 9, 16, 21])

### Dot Product (Used specifically for Vectors)

In [38]:
z = torch.dot(x, y)
z

tensor(46)

# -- Batch Matrix Multiplication --

In [40]:
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)  # Will be shape: (b x n x p)
out_bmm

tensor([[[3.4238, 3.8417, 3.5685,  ..., 3.5703, 4.8100, 4.5675],
         [5.2855, 6.1234, 4.9593,  ..., 5.2107, 7.3816, 7.7275],
         [4.5830, 3.5622, 3.4157,  ..., 3.4312, 5.3074, 4.9746],
         ...,
         [3.4342, 3.8357, 3.2583,  ..., 3.2414, 4.3260, 4.4927],
         [4.6908, 4.9731, 3.9796,  ..., 4.5289, 6.4835, 6.4278],
         [4.6140, 4.7881, 4.3090,  ..., 4.3557, 6.6817, 6.6317]],

        [[5.5663, 4.2936, 5.1691,  ..., 3.4019, 2.4863, 4.1179],
         [5.7247, 5.1422, 5.3619,  ..., 4.2943, 3.9218, 4.8550],
         [5.9615, 5.1008, 5.9645,  ..., 4.4299, 3.3086, 5.7118],
         ...,
         [7.0241, 7.2337, 6.7921,  ..., 5.3248, 4.0628, 7.2322],
         [4.6179, 4.3770, 3.6287,  ..., 2.3876, 2.4068, 3.1621],
         [4.4570, 4.0643, 3.9004,  ..., 2.5185, 2.3341, 3.4639]],

        [[5.1537, 4.6448, 5.6653,  ..., 5.0770, 3.9881, 6.2690],
         [5.7834, 4.6706, 6.3945,  ..., 4.2633, 3.3151, 6.2175],
         [5.6097, 4.3722, 6.2010,  ..., 5.0909, 3.8539, 5.

### Broadcasting

In [41]:
x1 = torch.rand((5, 5))
x2 = torch.ones((1, 5))
print(x1-x2)
print(x1*x2)

tensor([[-0.7316, -0.1894, -0.6852, -0.5786, -0.7450],
        [-0.6052, -0.4968, -0.5458, -0.3414, -0.1330],
        [-0.1833, -0.1913, -0.6064, -0.7221, -0.2065],
        [-0.4505, -0.8518, -0.2086, -0.7430, -0.4696],
        [-0.3132, -0.8965, -0.5556, -0.6306, -0.6463]])
tensor([[0.2684, 0.8106, 0.3148, 0.4214, 0.2550],
        [0.3948, 0.5032, 0.4542, 0.6586, 0.8670],
        [0.8167, 0.8087, 0.3936, 0.2779, 0.7935],
        [0.5495, 0.1482, 0.7914, 0.2570, 0.5304],
        [0.6868, 0.1035, 0.4444, 0.3694, 0.3537]])


In [42]:
x1 = torch.rand((5, 5))
x2 = torch.ones((5, 1))
print(x1-x2)
print(x1*x2)

tensor([[-0.3677, -0.7518, -0.2761, -0.1567, -0.2558],
        [-0.5587, -0.0668, -0.4092, -0.9877, -0.0058],
        [-0.2323, -0.3260, -0.3458, -0.8098, -0.4586],
        [-0.2180, -0.1578, -0.6630, -0.8686, -0.5869],
        [-0.2465, -0.0403, -0.3539, -0.4374, -0.5023]])
tensor([[0.6323, 0.2482, 0.7239, 0.8433, 0.7442],
        [0.4413, 0.9332, 0.5908, 0.0123, 0.9942],
        [0.7677, 0.6740, 0.6542, 0.1902, 0.5414],
        [0.7820, 0.8422, 0.3370, 0.1314, 0.4131],
        [0.7535, 0.9597, 0.6461, 0.5626, 0.4977]])


### Other useful tensor operations

In [ ]:
sum_x = torch.sum(x, dim=0)  # Sum of x across dim=0 (which is the only dim in our case), sum_x = 6

In [ ]:
values, indices = torch.max(x, dim=0)  # Can also do x.max(dim=0)
values, indices = torch.min(x, dim=0)  # Can also do x.min(dim=0)

In [ ]:
abs_x = torch.abs(x)  # Returns x where abs function has been applied to every element

In [ ]:
z = torch.argmax(x, dim=0)  # Gets index of the maximum value
z = torch.argmin(x, dim=0)  # Gets index of the minimum value

In [ ]:
mean_x = torch.mean(x.float(), dim=0)  # mean requires x to be float

In [ ]:
z = torch.eq(x, y)  # Element wise comparison, in this case z = [False, False, False]

In [ ]:
sorted_y, indices = torch.sort(y, dim=0, descending=False)

In [ ]:
z = torch.clamp(x, min=0)
# All values < 0 set to 0 and values > 0 unchanged (this is exactly ReLU function)
# If you want to values over max_val to be clamped, do torch.clamp(x, min=min_val, max=max_val)

In [ ]:
x = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)  # True/False values
z = torch.any(x)  # will return True, can also do x.any() instead of torch.any(x)
z = torch.all(
    x
)  # will return False (since not all are True), can also do x.all() instead of torch.all()